<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLdfbxsp\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLdfbxsp/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerLdfbxsp.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerLdfbxsp\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerLdfbxsp\appDevDebugProjectContainer([
    'container.build_hash' => 'Ldfbxsp',
    'container.build_id' => 'a904ac24',
    'container.build_time' => 1583228369,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLdfbxsp');
